apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: lab8
        image: lab8:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db_password
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: HOST
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: DATABASE
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: PORT
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer