apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-deploy
  template:
    metadata:
      labels:
        app: app-deploy
    spec:
      containers:
      - name: lab8
        image: python:3.10-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: app-deploy
          mountPath: /mnt/data
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db_password
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: HOST
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: DATABASE
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: PORT
      volumes:
      - name: app-deploy
        persistentVolumeClaim:
          claimName: app-deploy-pvc